### PR TITLE
Enable transparent mode

### PR DESCRIPTION
**Pull request by lbrdar**
I've added the 'transparent' bool prop to enable custom background and content behind the circle progress component.

### CODE REVIEW

**Comment by Jacse** [comment]
To be honest, I think we should just set the style to tranparent as default, without the prop. If a user wants a background color they should be able to set it using the `style`-prop. Thoughts?

**Comment by lbrdar** [comment]
Hi Jacse,

you are right, I can't find a reason why someone would need this to be false so we can just set it to be transparent always.  
This new commit does exactly that.

**Comment by Jacse** [comment]
Great! Also, the `backgroundColor` prop on the `childContainerStyle` is not necesarry as it's transparent by default. So if you could remove that change and just add the transparent background on the `<Surface>` that would be awesome!

**Comment by lbrdar** [comment]
Done! :)

**Comment by Jacse** [comment]
Perfect!

**Pull request merged**
