### PR TITLE
Ported to Android

### PR DESCRIPTION
**Pull request by gunters63**
Upgraded example project to React 0.20.0

### CODE REVIEW

**Comment by gunters63** [comment]
Hi Bart, 

I ported your component to React Native for Android.
Should work on React Native 0.20.0 onwards, the example behaves and looks exactly the same as on iOS.

The solution looks a bit hacky because:
- Android does not support strokeDash, so I had to draw a correct circle segment.
- ART does not support drawing arbitrary circle segments (seems to be limited to half circles), so I had to fall back to using internal drawing primitives.
- Also, the Android version of ART behaves differently (buggy?) than the IOS one, so I had to use platform specific code.

**Comment by bgryszko** [comment]
Hey Gunter, this looks really good! Have you tested it on iOS as well?

**Comment by gunters63** [comment]
Yes, side by side, Looked exactly the same.

**Comment by bgryszko** [comment]
Awesome!

**Pull request merged**
