### PR TITLE
Added strokeCap, capWidth and capColor options

### PR DESCRIPTION
**Pull request by jaysson**
- Strokecap can now be customised through props
- I wanted a circular cap at the end of the progress. Added capwidth and capcolor options to accommodate that
- Introduced couple of variables (center, radius)

All new properties are optional. Old behaviour is retained if new properties are not specified.

### CODE REVIEW

**Comment by mklb** [comment]
Would love to see this merged 😍

**Comment by bgryszko** [comment]
Sorry for late response. Can you update the docs as well?

**Comment by renso3x** [comment]
Hi @jaysson I have used your changes and looks great. But there is something on the background path of the circle the circle path is being cut in half on the center and the borders of the paths. 

screen shot 2017-10-12 at 7 19 12 pm

**Comment by Jacse** [comment]
@jaysson Are you up for rebasing this and fixing a few errors, or would you like me to implement your changes?

There are a few things we need to fix before merging:
1. Rebase the PR (linecap has been introduced, though the casing is off if you want to fix to lineCap)
2. The cap-circle gets cut off as shown by @renso3x 
3. Please make the cap optional and only include the `Shape` if `capWidth` is defined. Make `capColor` default to `tintColor`

**Comment by Jacse** [comment]
Closing for inactivity.

**Pull request closed without merging**
