### PR TITLE
Add support for partial arcs

### PR DESCRIPTION
**Pull request by alarner**
I was trying to implement a UI like the picture below shows and wanted the progress bar to encapsulate an arc instead of a full circle.

image

I've added a new prop called `arcSweepAngle` that allows you to specify the angle that the arc should encompass. Thought you might be interested in adding this functionality upstream as well.

### CODE REVIEW

**Comment by bgryszko** [comment]
That is neat, thanks! Can you make it optional, so default functionality is preserved when people will update the component :) ?

**Comment by alarner** [comment]
@bgryszko it should already be optional since the default value is a 360 degree arc. Let me know if you see something that I'm missing.

**Comment by bgryszko** [comment]
Hey @alarner, take a look at https://github.com/bgryszko/react-native-circular-progress/pull/50/commits/bcea788d704565d90fb51f144a812d15cd4bc4d1#diff-5b016fae9609a8fd01bf9d1318e108f4L46 – default value for `rotation` was `{rotation - 90}` and now is `{rotation}`

**Comment by jackread** [comment]
This looks amazing...  just what I need 👍

**Pull request closed without merging**
