### PR TITLE
Feature/align children center

### PR DESCRIPTION
**Pull request by ayushinigam**
This PR fixes the alignment of children.
Now the children element will be automatically centre aligned.

### CODE REVIEW

**Comment by lordakshaya** [comment]
@bgryszko can we have this PR merged and update the npm module? I believe this is a good feature and of value for the community. At the moment, we have to use the dependencies thru the forked PR but it would be good if we can revert back to using the npm module.

**Comment by readthecodes** [comment]
I need this feature!!!!!!!!!!

**Comment by lordakshaya** [comment]
@markusl Thanks mate for merging in the PR!!! Possible to release the new version of the npm module with this commit?

**Comment by Jacse** [comment]
I'm not sure we should set `alignItems` and `justifyContent` explicitly since the user could do that easily to achieve the same effect. On the other hand, I guess most use cases would have the children centered, and one could always create a full-width component to left-align children if need be.

One small change I'll add is moving the styles to a separate Style-object.

**Comment by markusl** [comment]
Good points @Jacse, sounds like something to be added to readme instructions.

**Pull request merged**
