### PR TITLE
Add callback for when animation completes

### PR DESCRIPTION
**Pull request by alechewitt**
Just added in a callback for when the animation completes.

### CODE REVIEW

**Comment by soledaddiez** [comment]
Hi, I was just planning to do a PR with the same change, but I think the callback needs to be included also when 'start' is called on 'performLinearAnimation'.
Is there any reason not to do that?.

**Comment by alechewitt** [comment]
No reason not to do that. I must have just missed it. Feel free to add to this PR.

**Comment by soledaddiez** [comment]
Sorry, I was having this ready in for my own PR https://github.com/bgryszko/react-native-circular-progress/pull/76/files

**Comment by markusl** [comment]
Fixed in #76

**Pull request closed without merging**
